### ISSUE TITLE
Embedding node type

### ISSUE THREAD

**Issue by matcyr** [jrwnter/pigvae#4]
Hi,

In the GraphEncoder.add_emb_node_and_feature,
        edge_features[:, 0, :, edge_dim] = 1
        edge_features[:, :, 0, edge_dim] = 1
I believe these two lines are trying to give the embedding edge a new type right? Why we don't have a similar code for embedding node type like:
node_features[:,0,node_dim] = 1

Thanks,
Yurui

**Comment by jrwnter** [comment]
Hi,
good catch. looking in my git history, I might removed this one-hot encoding of the empty node unintentionally. It might be irrelevant for the performance though (no difference for the network if we encode embedding nodes by a zero vector or a one-hot vector). I will check that. Closing for now
